name: rl-algos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - pyyaml>=6.0
  - tqdm>=4.62.0
  - jupyter>=1.0.0
  - pip:
    - mujoco>=2.3.0
    - gymnasium>=0.28.0
    - stable-baselines3>=2.0.0
    - sb3-contrib>=2.0.0
    - tensorboard>=2.8.0
    - wandb>=0.13.0
    - optuna>=3.0.0
    - hydra-core>=1.2.0
    - omegaconf>=2.2.0
    - rich>=12.0.0
    - typer>=0.6.0
